name: Flutter_iOS

on:
  workflow_dispatch:
    inputs:
      target:

jobs:
  build_ios:
    runs-on: macos-13

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app
      
        run: |
          flutter devices
          flutter build ios --release --no-codesign -d macos
                   
      - name: Export IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release CODE_SIGNING_REQUIRED=NO -sdk iphoneos -archivePath build/ios/archive/MyApp.xcarchive archive
          xcodebuild -exportArchive -archivePath build/ios/archive/MyApp.xcarchive -exportOptionsPlist ios/Runner/Info.plist -exportPath build/ios/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-IPA
          path: build/ios/ipa/*.ipa
