name: Flutter_iOS

on:
  push:
    branches: [main]

jobs:
  build_ios:
    runs-on: macos-13

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.6'
    - name: Build Flutter
      run: |
           flutter pub get
           flutter run 
           flutter build apk --release --target-platform=android-arm64
#    - name: Publish iOS Artefacts
#      uses: actions/upload-artifact@v1
#      with:
 #       name: release-ios
 #       path: ios
