name: Flutter_iOS

on:
  push:
    branches: [main]

jobs:
  build_ios:
    runs-on: macos-13

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app
      
        run: |
          flutter devices
          flutter build ios --release --no-codesign -d macos
          xcodebuild -workspace ios/Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath build/ios/archive/MyApp.xcarchive \
                   archive CODE_SIGNING_REQUIRED=NO
                   
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/MyApp.xcarchive \
            -exportOptionsPlist ios/Runner/Info.plist \
            -exportPath build/ios/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-IPA
          path: build/ios/ipa/*.ipa
