name: Flutter_Build

on:
  push:
    branches: [main]

jobs:
  build_ios:
    runs-on: macos-13

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.6'

    - name: Fetch dependencies
      run: flutter pub get

    - name: Build iOS archive
      run: |
        flutter build ios --release
        xcodebuild -workspace ios/Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath build/ios/archive/MyApp.xcarchive \
                   archive
      env:
        CI: true

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath build/ios/archive/MyApp.xcarchive \
                   -exportOptionsPlist ios/Runner/Info.plist \
                   -exportPath build/ios/ipa
      env:
        FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.13.6-x64
        PUB_CACHE: /Users/runner/.pub-cache

    - name: Publish iOS Artefacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: ios-release
        path: build/ios/ipa
